# Generated by Django 5.2.11 on 2026-02-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_experience_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("duration", models.CharField(max_length=100)),
                (
                    "result_details",
                    models.CharField(help_text="GPA or Marks", max_length=200),
                ),
                (
                    "degree_image",
                    models.ImageField(blank=True, null=True, upload_to="degrees/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experience",
            name="degree_image",
            field=models.ImageField(blank=True, null=True, upload_to="degrees/"),
        ),
    ]
